service: hello-thundra

custom:
  thundraApiKey: #TODO: enter your API key here
  stage: dev #Configure your stage if you want
  region: us-west-2 #Configure your AWS region if you want
  profile: default #Configure your AWS profile if you want

provider:
  name: aws
  runtime: python3.6
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  profile: ${self:custom.profile}
  memorySize: 256
  timeout: 300
  environment:
      thundra_apiKey: ${self:custom.thundraApiKey}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:*
      Resource: [
        "*"
      ]

functions:
  hello-thundra:
    name: hello-thundra
    handler: hello_world.handler
  hello-world:
    name: hello-world
    handler: thundra.handler.wrapper
    environment:
      thundra_agent_lambda_handler: hello_world_service.handler

